#+TITLE: Chemistry notez
#+STARTUP: latexpreview

* Concepts
** What is Lattice energy
THe energy of formation of one mole of solid crystallline ionic compund from its
gaseous ions. Lattice energy is negative.

** What affects the strength of an ionic bond.

*** Magnitude of ion charges (more important)
The higher the magnitude of charges, the more exothermic is its lattice energy.

*** Distance between the ions
Smaller the ions, the more exothermic is its lattice energy.

** What affects the strength of a covalent bond

*** size of the atom

AS size of the atom becomes smaller, the bond energy increases

*** bond multiplicity

As multiplicity of bonds between atoms increases, the atoms are held more
tightly and more closely together, thus the bond length decreases and BE
increases.

** What affects the strength of a metallic bond?

- Valence electrons
- size of metallic cation

** What is electron affinity

Refers to the energy change when an electron is added to a gaseous atom. The
more negative the energy change when an electron is added, the greater the
electron affinity. Increases accross period.

** Why is phosphorus allowed to expand its octet

It can expand its octet to accomodate additional electrons because one of the
electrons in the 3s valence subshell can be promoted to a vacant 3d orbital.

** what are the spdf's?

1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 4f14 5s2 5p6 5d10 5f14 6s2 6p6 6d10 7s2
7p6

** What are co-ordinate bonds?

When a molecule which is electron-deficient accepts a lone pair donated by a
donor atom

** What are the assumptions of Valence-shell electron-pair repulsion

1. molecular geometry depends on electron domain geometry
2. Multiple bonds treated as single bons

3. electron pairs want to minimise repulsion
4. lp-lp > lp-Bp > Bp-Bp

** Electron domain geometry

*** 2 Electron domains:: Linear
1. Linear - 180

*** 3 Electron domains:: Trigonal planar
1. Trigonal planar - 120
2. Bent - 119

*** 4 electron domains:: Tetrahedral
1. Tetrahedral - 109.5
2. Trigonal pyramidal - 107
3. Bent - 104.5

*** 5 electron domains:: Trigonal bipyramidal
1. Trigonal bipyramidal - 90/120
2. Seesaw - <90/<120
3. T-shaped - 90
4. Linear - 180

*** 6 electron domains:: octahedral
1. Octahedral - 90
2. Square pyramidal - ~90
3. Square planar - 90
4. T-shaped - 90
5. Linear - 180

** Limitations of VSEPR
- isoelectronic species
- transitional metal compounds

** What effects do multiple bonds have on bond angle
double and triple bonds possess greater electron density as compared to single
bonds. therefore multiple bonds also occupy more space as compared to electron
domains of single bonds and reduce the bond angles.

** What affects DDF?

*** Polarity of the molecule
the more polar a molecule, the stronger the dipole dipole forces when comparing
molecules of similar mass.

** What affects LDF

*** Molecular size which determines the size of electron cloud of a molecule

(polarisability: The tendency of an electron cloud to distort due to
instantaneous dipole induced dipole)

*** Shape of a molecule

(compactness and S.A.)

** Why does ice float on water.

In ice the water molecules are in an ordered arrangement held by hydrogen bonds
which prevent the water molecules from coming any closer. thus ice has a more
open structure with more empty space and is less dense.

When ice melts, the structure collapses. The hydrogen bonds between different
water molecules break and reform as a result as a result of the random motion
allowing te molecules to come closer together hence density increases.

** Why does ion-dipole force is strong?
When KCl is dissolved in water, numerous ion-dipole interactions are formed
between the ions and the water molecules.  The overall strength of the
ion-dipole interactions can overcome the ionic interactions (present in KCl) and
the hydrogen bonding (present in water). Hence KCl dissolves in water

* Model answers
** Trigonal pyramidal from tetrahedral with weird bond angles

*** Why does NH3 have a bond angle of 107 ?

The NH3 bond angle is 107. This is distorted from the pure tetrahedral angle of
109.5 degrees due to the lone pair taking up more space than the single bond.

*** Why does NF3 have a bond angle of 102 ?
The NF3 bond angle is 102°. There is more distortion as compared to
NH3. Fluorine is more electronegative than hydrogen and the electron density in
the N–F bond is skewed towards fluorine. The electrons in the single N-F bonds
are further from the central atom (nitrogen), decreasing repulsion between these
bonding pair electrons. Thus, bond angle decreases.

*** Why does CH3Cl have a bond angle of 110.5 ?

The (HCH) bond angle in CH3Cl is 110.5°. The HCH bond angle is wider than in CH4
which suggests that the C–Cl single bond has less electron density closer to the
carbon atom. This is due to the C–Cl bond polarity with δ– on chlorine, as
chlorine is more electronegative than carbon (and hydrogen). The C–H bond has
more electron density around the carbon because carbon is more electronegative
than hydrogen.

*** Why does H2O have a bond angle of 104.5 ?

This is greater distortion than in NH3 as there are 2 lone pairs on the oxygen

*** Why does H2S have a bond angle of 92.2 ?
The H2S bond angle is 92.2°. There is a surprisingly large difference between
this and the bond angle in H2O. Sulfur is less electronegative than oxygen, so
there is less electron density around the central sulfur atom in H2S compared to
the central oxygen atom in H2O. The repulsion between the bonding pair electrons
decrease, decreasing the bond angle.


** Expanded Octet

*** Why does nitrogen only form NCl3 while phosphorus forms PCl3 and PCl5 ?

Nitrogen is in period 2 which has 2 valence subshells, 2s & 2p which can hold a
maximum of 8 valence electrons. Thus, the N atom forms 3 covalent bonds with CL
to form NCl3.

Phosphorus is in period 3 which has 3 valence subshells, 3s,3p and 3d.  Thus
period 3 elements can expand their octet to accomodate additional electrons
since electrons from 3s subshell can be promoted to a vacant 3d-orbital, thus
phosphorus forms 2 chlorides.


** Ionic radius

*** Difference in melting point between sodium chloride
Bromide ion is larger in size compared to chloride ion resulting its lattice
energy having a smaller magnitude than the lattice energy of sodium chloride.

Less energy is needed to overcome the weaker electrostatic forces of attraction
between sodium and bromide ions as compared to between sodium and chloride ions,
resulting in a lower melting point for sodium bromide.

** Magnitude of charges
*** Difference in melting point between sodium chloride and magnesium oxide

The magnitude of charges on Na+ and Cl- is lower than that of Mg2+ and O2- so
the lattice energy of NaCl is less exothermic than that of MgO.

** Electroconductivity in solid vs molten for ionic structures

*** "Why is this true for NaCl and MgO"
NaCl and MgO are ionic structures which consist of oppositely charged ions held
together by strong ionic bond in a regular 3-dimensional lattice. In solid
state, there are no mobile charged particle sthat can acts as charge
carriers. However in molten state, the mobile oppositely charged ions can act as
charge carriers and thus, conduct electricity

** ionic structures vs simple covalent in terms of bp at rtp
*** NaCl vs Cl2
Sodium chloride is ionic structure that made up of oppositely charged ions held
together by strong ionic bonds in a regular 3-dimensional lattice which requires
more energy to overcome.  Thus, at room temperature, sodium chloride exists as
solid. Chlorine gas comprises of simple molecular structure that are made up of
discrete covalent molecules that are held together by weak intermolecular forces
which are easily overcomed. Thus, at room temperature, chlorine gas exists as
gas.

** Metallic structures increase in conductivity accross period

*** "Why"
Electrical conductivity increases from sodium to aluminum. Na, Mg and Al are
metals with positive ions surrounded by a sea of mobile delocalized electrons
which act as charge carriers. Hence, they show high electrical
conductivity. From Na to Al, the number of valence electrons contributed to the
“sea” increases from 1 in Na to 3 in Al.  Hence, with more mobile charge
carriers, electrical conductivity increases

** Resonance

*** why is the does so3 have a bond length of 1.42 while so32- has a bond length of 1.51?

From the Lewis structures, the SO3structure has three S=O bonds (S-O bond order
= 2), as compared to the hybrid of reasonance structures in SO32-(S-O bond order
=4/3, 4 bonds shared by 3 sets of S-O)

** Identifying similar organic compounds

- Check if the longest continuous chain has the same number of C
- Check if branches are the same and are at the same locations

** Bond length proportion to bond multiplicity

*** "Why is the bond length not proportional to the no/ of bonds"
The nature of the bonds in a single bond and double/triple bond are not the
same.  So the increase in bond energy/decrese in bond length will not be in
proportion.

hybridization

** Explain why the heat of vaporization is always greater than the heat of fusion
Moreenergy is required to separate particles completelythan to just free them
from their fixed positions as the inter-particle spacing in gases is much larger
in liquids




** LDF - Molecular size
*** Why is fluorine a gas at rtp while bromine is a liquid at rtp.

Both fluorine and bromine have simple molecular structure. The molecules are
*non-polar* and are held by *LDF*.

As fluorine has a *smaller molecular size*, its *smaller elctron cloud is less
easily polarized*, resulting in weaker LDF. The *average kinetic energy of the
molecules at room condition is sufficient* to overcome the weaker LDF, hence
fluorine is a gas.

As bromine has a *larger molecular size*, its *larger electron cloud is more
easily polarized* , resulting in stronger LDF. The average kinetic energy of the
molecules at room conditions is insufficient to overcome the stronger LDF, hence
it is a liquid.

** LDF - Shape

*** "Why is the bp of 2,2-dimethylpropane lower than that of pentane"

Both compounds are simple molecules. They are non-polar and have similar
molecular size.

2,2-dimethylpropane molecules are *spherical* in shape and a smaller surface
area of contact resulting in a weaker LDF. Hence, less energy is required to
overcome weaker LDF. Pentane molecules are *elongated* and have a larger surface
area of contact which resulted in stronger LDF interations. Hence more energy is
required to overcome the stronger LDF, resulting in higher boiling point.

** HB - Extensiveness of bonds

*** Why does N2H4 have greater bp than CH3NH2

Both compounds have simple molecular structure. The molecules are polar and are
held by hydrogen bonds.

Hydrazine forms more extensive hydrogen bonds than methylamine. Thus, more
energy is required to overcome the hydrogen bonds in hydrazine compared to
methylamine, resulting in higher boiling point.

** DDF - Polarity

*** CH3Cl has dipole moment of 1.87D and CH3I has dipole moment of 1.62D. Which substance will have greater DDF?

DDf increases in magnitude as the dipole moment of the molecule increases.  Alt:
The C-Cl bond is more polar than C-I bond. The C-H bonds in the molecules are
relatively non-polar.

Thus, there is stronger DDF in CH3Cl molecules than between CH3I molecules.

** LDF and HB vs LDF-only

*** "Why do pentane and butanol have different boiling points"

Since both pentane and butanol have similar molecular sizes, thus the same
electron cloud size and same polarizability, the london dispersion forces are of
similar strength.

However, butanol has hydrogen bonds between its molecules.

The intermolecular forces of butanol is stronger, hence more energy is required
for vaporization, resulting in slower rate of vaporization.

** HB vs LDF
*** Why do dimethylether and ethanol have different boiling points?

Both dimethylether and ethanol have similar molecular size, thus the same
electron cloud size and similar polarizability, thus these two compounds have
similar LDF.

The HB in ethanol molecules are stronger than the DDF in dimethylether. Thus,
more energy is required to overcome the stronger HB between the ethanol
molecules, a higher boiling point is observed for ethanol.
** Solubility
*** Why is toluene less soluble than phenol?
When toluene is mixed with water the interactions between two different
compounds is Dipole-induced dipole forces. These interactions are weaker than
the HB between water molecules before mixing. Hence toluene will not dissolve in
water.

When phenol is mixed with water, the interactions between the two different
compounds is HB. These interactions are more similar in strength to the HB
present between phenol and water before mixing - so phenol is more soluble in water.

** surface tension

The molecules in the bulk have attractive intermolecular forces on all sides,
pulling from all directions. These interations minimise the energy of these
molecules.

Molecules at the surface have less interations which makes them less stable due
to their higher potential energy. The net force on the surface molecules is
inward, and they cluster together to minimize surface area.


* Hydrocarbons

** Alkanes
   - less dense than water
   - Saturated hydrocarbons
   - Unreactive
*** Cracking
    - alkane --> alkene + alkane
    - Important as bigger alkanes can be broken down to smaller alkenes and
    alkanes which can be used for more fuel
*** Alkane types
**** C1-C4
     - Gas at room temperature
     - Used as gas fuels
**** C5-C17
     - Liquid
     - Gasoline/petrol is a mixture of C5-C8
     - Motor oil, kerosene, diesel:: C9-C16
**** C17+
     - Solid
     - Paraffin wax
     - How does petroleum jelly prevent diager rash?
       - It  coats the area with a protective gel layer that prevents moisture
     from getting next to skin.
*** Combustion/oxidation
\[
C_nH_{2n+2} + \frac{3n+1}{2}O_2 \xrightarrow{\textit{flame}} nCO_2 + (n+1)H_2O
\]
(requires flame)

Complete combustion (blue flame) occurs with sufficient oxygen

Incomplete combustion occurs with greater C atoms.

Soot (C particles) and CO (poisonous, odourless and colorless gas) are produced

*** Substitution reaction

\[
C_nH_{2n+2}  + X_2 \xrightarrow{UV,rtp} C_nH_{2n+1}X + HX
\]

chain reaction

requires UV light as a catalyst at rtp

Detectable acidic fumes with litmus paper. (HCl and HBr fumes are white)

** Alkenes

Low density
Alkenes with several double bons have a color associated with them.

*** Combustion
\[
C_nH_{2n} + \frac{3n}{2}O_2 \xrightarrow{\textit{flame}} nCO_2 + nH_2O
\]

Requires heat

*** Hydrogenation/Halogenation
Alkene + Hydrogen $\rightarrow$ Alkane
Requires palladium/Platinum/Nickel + heat + pressure

Alkene + Halogen $\rightarrow$ Alkyl Halide
requires rtp

** Alkynes

*** Combustion
\[
C_nH_{2n-2} + \frac{3n-1}{2}O_2 \xrightarrow{\textit{flame}} nCO_2 + (n-1)H_2O
\]

Requires heat

*** Hydrogenation/Halogenation
Alkyne + 2 Hydrogen $\rightarrow$ Alkane
Requires palladium/Platinum/Nickel + heat + pressure

Alkyne + Halogen $\rightarrow$ Alkyl Halide
Require rtp

** Aromatic

Non-polar
Volatile
Flammmable with a sooty flame
Toxic, carcinogenic (some)
substituents on benzene ring modify these properties

*** Halogenation/Hydrogenation

\[
C_nH_n + X_2 \xrightarrow{Fe/FeX_3/AlX_3} C_nH_{n-1}X + HX
\]

Requires Fe/FeX3/AlX_3


*** Alkylation (Friedal-Crafts)
Benzene + R-X $\xrightarrow{AlX_3}$ R-Benzene + HX

Requires AlX3

*** Heterocyclic aromatic compounds
Heterocyclic aromatic compunds consist of at least one atom other than carbon
