#+TITLE: Chemistry notez
#+STARTUP: latexpreview
#+OPTIONS: toc:nil

* Concepts
** What is Lattice energy
THe energy of formation of one mole of solid crystallline ionic compund from its
gaseous ions. Lattice energy is negative.

** What affects DDF?

*** Polarity of the molecule
the more polar a molecule, the stronger the dipole dipole forces when comparing
molecules of similar mass.

** What affects LDF

*** Molecular size which determines the size of electron cloud of a molecule

(polarisability: The tendency of an electron cloud to distort due to
instantaneous dipole induced dipole)

*** Shape of a molecule

(compactness and S.A.)


** " HB
- Extensiveness (greater factor)
- Dp moment

** Why does ice float on water.

In ice the water molecules are in an ordered arrangement held by hydrogen bonds
which prevent the water molecules from coming any closer. Thus ice has a more
open structure with more empty space and is less dense. When ice melts, the
structure collapses. The hydrogen bonds between different water molecules break
and reform as a result as a result of the random motion allowing te molecules to
come closer together hence density increases.

** Why does ion-dipole force is strong?
When KCl is dissolved in water, numerous ion-dipole interactions are formed
between the ions and the water molecules.  The overall strength of the
ion-dipole interactions can overcome the ionic interactions (present in KCl) and
the hydrogen bonding (present in water). Hence KCl dissolves in water
** Which IMF would win in a fight?
1. Ion-dipole forces
2. Hydrogen Bonding
3. Dipole dipole forces
4. Ion-induced dipole forces
5. dipole-induced dipole forces
6. London Dispersion forces
* Model answers

** LDF - Molecular size
*** Why is fluorine a gas at rtp while bromine is a liquid at rtp.

Both fluorine and bromine have simple molecular structure. The molecules are
*non-polar* and are held by *LDF*.

As fluorine has a *smaller molecular size*, its *smaller elctron cloud is less
easily polarized*, resulting in weaker LDF. The *average kinetic energy of the
molecules at room condition is sufficient* to overcome the weaker LDF, hence
fluorine is a gas.

As bromine has a *larger molecular size*, its *larger electron cloud is more
easily polarized* , resulting in stronger LDF. The average kinetic energy of the
molecules at room conditions is insufficient to overcome the stronger LDF, hence
it is a liquid.

** LDF - Shape

*** "Why is the bp of 2,2-dimethylpropane lower than that of pentane"

Both compounds are simple molecules. They are non-polar and have similar
molecular size.

2,2-dimethylpropane molecules are *spherical* in shape and a smaller surface
area of contact resulting in a weaker LDF. Hence, less energy is required to
overcome weaker LDF. Pentane molecules are *elongated* and have a larger surface
area of contact which resulted in stronger LDF interations. Hence more energy is
required to overcome the stronger LDF, resulting in higher boiling point.

** HB - Extensiveness of bonds

*** Why does N2H4 have greater bp than CH3NH2

Both compounds have simple molecular structure. The molecules are polar and are
held by hydrogen bonds.

Hydrazine forms more extensive hydrogen bonds than methylamine. Thus, more
energy is required to overcome the hydrogen bonds in hydrazine compared to
methylamine, resulting in higher boiling point.

** DDF - Polarity

*** CH3Cl has dipole moment of 1.87D and CH3I has dipole moment of 1.62D. Which substance will have greater DDF?

DDf increases in magnitude as the dipole moment of the molecule increases.  Alt:
The C-Cl bond is more polar than C-I bond. The C-H bonds in the molecules are
relatively non-polar.

Thus, there is stronger DDF in CH3Cl molecules than between CH3I molecules.

** LDF and HB vs LDF-only

*** "Why do pentane and butanol have different boiling points"

Since both pentane and butanol have similar molecular sizes, thus the same
electron cloud size and same polarizability, the london dispersion forces are of
similar strength.

However, butanol has hydrogen bonds between its molecules.

The intermolecular forces of butanol is stronger, hence more energy is required
for vaporization, resulting in slower rate of vaporization.

** HB vs LDF
*** Why do dimethylether and ethanol have different boiling points?

Both dimethylether and ethanol have similar molecular size, thus the same
electron cloud size and similar polarizability, thus these two compounds have
similar LDF.

The HB in ethanol molecules are stronger than the DDF in dimethylether. Thus,
more energy is required to overcome the stronger HB between the ethanol
molecules, a higher boiling point is observed for ethanol.

** Solubility
*** Why is toluene less soluble than phenol?

When toluene is mixed with water the interactions between two different
compounds is Dipole-induced dipole forces. These interactions are weaker than
the HB between water molecules before mixing. Hence toluene will not dissolve in
water.

When phenol is mixed with water, the interactions between the two different
compounds is HB. These interactions are more similar in strength to the HB
present between phenol and water before mixing - so phenol is more soluble in water.

** surface tension

The molecules in the bulk have attractive intermolecular forces on all sides,
pulling from all directions. These interations minimise the energy of these
molecules.

Molecules at the surface have less interations which makes them less stable due
to their higher potential energy. The net force on the surface molecules is
inward, and they cluster together to minimize surface area.

** Why does heptadecasexanol dissolve more readily in hexane than water
   As the length of the hydrocarbon chain increases, the highly polar O-H bond
   group becomes a smaller part of the molecule and the higher molecular size
   alcohol behaves more like a non-polar molecule therefore solubility in water
   decreases.

(maybe continue to elaborate as stated in "Solubility" two blocks yonder)

** connect strong IMF = Great viscosity
<explain IMF>

This holds the molecules of X more strongly together, preventing them from
moving readily. Hence, it's more viscous.

* Hydrocarbons
** Alkanes
   - less dense than water
   - Saturated hydrocarbons
   - Unreactive
*** Cracking
    - alkane $\rightarrow$  alkene + alkane
    - Requires heat, catalyst
    - Important as bigger alkanes can be broken down to smaller alkenes and
    alkanes which can be used for more fuel
*** Effect of greater carbon count on usefulness as fuel
Greater boiling point could result in incomplete combustion due to insufficient
temperature of the combustion engine - Increase temperature of combustion engine to fix it

Greater carbon content so combustion would result in more sooty flame - Increase
air-fuel ration to increase oxygen intake to fix it

*** Alkane types
**** C1-C4
     - Gas at room temperature
     - Used as gas fuels
**** C5-C17
     - Liquid
     - Gasoline/petrol is a mixture of C5-C8
     - Motor oil, kerosene, diesel C9-C16
**** C17+
     - Solid
     - Paraffin wax
     - How does petroleum jelly prevent diager rash?
       - It coats the area with a protective gel layer that prevents moisture from getting next to skin.
*** Combustion/oxidation

\[
C_nH_{2n+2} + \frac{3n+1}{2}O_2 \xrightarrow{\textit{flame}} nCO_2 + (n+1)H_2O
\]
(requires flame)

Complete combustion (blue flame) occurs with sufficient oxygen

Incomplete combustion occurs with greater C atoms.

Soot (C particles) and CO (poisonous, odourless and colorless gas) are produced

*** Substitution reaction

\[
C_nH_{2n+2}  + X_2 \xrightarrow{UV,rtp} C_nH_{2n+1}X + HX
\]

chain reaction

Requires UV light as a catalyst at rtp

Detectable acidic fumes with litmus paper. (HCl and HBr fumes are white)

** Alkenes

Low density
Alkenes with several double bonds have a color associated with them.

*** Combustion
\[
C_nH_{2n} + \frac{3n}{2}O_2 \xrightarrow{\textit{flame}} nCO_2 + nH_2O
\]

Requires heat

*** Hydrogenation/Halogenation
Alkene + Hydrogen $\rightarrow$ Alkane

Requires palladium/Platinum/Nickel + heat + pressure

Alkene + Halogen $\rightarrow$ Alkyl Halide
requires rtp

** Alkynes

*** Combustion
\[
C_nH_{2n-2} + \frac{3n-1}{2}O_2 \xrightarrow{\textit{flame}} nCO_2 + (n-1)H_2O
\]

Requires heat

*** Hydrogenation/Halogenation
Alkyne + 2 Hydrogen $\rightarrow$ Alkane
Requires palladium/Platinum/Nickel + heat + pressure

Alkyne + Halogen $\rightarrow$ Alkyl Halide
Require rtp
