#+TITLE: Analysis
#+HUGO_SECTION: Math
#+STARTUP: latexpreview
#+LATEX_HEADER: \input{~/.emacs.d/latexheader.tex}

* Real numbers

*Theorem*

There exists an ordered field R which has the least-upper-bound property. R contains Q as a subfield


*Theorem*
If $x \in R$, $y \in R$, and $x > 0$, then there's a positive integer $n$ such that $nx > y$.
If $x < y$, then there exists a $p \in Q$ such that $x < p < y$

*Theorem*

For every positive real x and every positive integer n, there is only one positive real y such that $y^n = x$

*Defintion*

An ordered field is a field which is an ordered set, such that:

1. $x + y < x + z$ and  $y < z$
2. $xy > 0$ and $x > 0, y > 0$

* Sequences

A sequence converges if it fulfills epsilon-delta, i.e. for every $\epsilon > 0$, there is an integer N, such that $n \geq N$ implies $d(p_n,p) < \epsilon$.

*Other properties*

1. Every neighbourhood of p contains $p_n$ for all but finitely many $n$.
2. If $E \subset X$, and $p$ is a limit point of E, then there is a sequence $\{p_n\}$ in $E$ such that $p = \lim_{n\to\infty} p_n$.


*Definition*

If a subsequence of a sequence converges, its limit is called a subsequential limit of the sequence. A sequence only converges iff every subsequence of $\left{p_n\right}$ converges to p.

#+BEGIN_theorem
1. If $\{p_n\}$ is a sequence in a compact space X, the nsome subsequence of $\{p_n\}$ converges to a point of X.
2. Every bounded sequence in $R^k$ contains a convergent subsequence.
#+END_theorem

#+BEGIN_theorem
The subsequential limits of a sequence $\{p_n\}$ in a metric space X form a closed subset of X.
#+END_theorem


** Cauchy sequences

A sequence $\{p_n\}$ is a Cauchy sequence iff for every $\epsilon > 0$ there is an integer N such that $d(p_n,p_m) < \epsilon$ if $n,m \geq N$.

Let E be a nonempty subset of a metric space X, and let S be the set of all real numbers of the form $d(p,q)$, with $p\in E$ and $q\in E$. THe sup of S is called the diameter of E.

If $E_N$ is the set of all points $p_{N+i}$, then $\{p_n\}$ is a Cauchy sequence iff $\lim_{N\to\infty} \text{diam} E_N = 0$.

*Theorem*
1. If $\bar{E}$ is the closure of a set $E$ in a metric space X, then $\text{diam } \bar{E} = \text{diam } E$.
2. If $K_n$ is a sequence of compact sets in X such that $K_{n+1} \subset K_n$, and its diameter tends to 0 with n, then the intersection consists of exactly one point.


*Theorem*
1. In any metric space X, every convergent sequence is a Cauchy sequence.
2. If X is a compact metric space and if $\{p_n\}$ is a Cauchy sequence in X, then $\{p_n\}$ converges to some point of X.
3. In $R^k$, every Cauchy sequence converges.


*Definition*

A metric space in which every Cauchy sequence converges is complete.

*Theorem*

A monotonic sequence converges iff it is bounded.

** Upper and lower limits

*Definition*
Let E be the set of all subsequential limits of a sequence $s_n$.

\[
s^* = \sup E = \lim_{n\to\infty} \sup s_n
\]

\[
s_* = \inf E = \lim_{n\to\infty} \inf s_n
\]

*Theorem*

1. $s^* \in E$
2. If $x > s^*$, there is an integer, there is an integer $N$ such that $n \geq N$ implies $s_n < x$.

   Moreover, $s^*$ is the only number with the two properties.

** Convergence

*Definition*

Cauchy criterion:

$\sum a_n$ converges iff for every $\epsilon > 0$, there is an integer $N$ such that:

\[
\left\vert \sum_{k=n}^m a_k \right\vert \leq \epsilon
\]

if $m \geq n \geq N$.

or when m equals n,

\[
\vert a_n \vert \leq \epsilon
\]


*Theorem*

Suppose $a_n$ is non-negative monotonically decreasing sequence. Then its series converges iff the following series converges:

\[
\sum_{k=0}^\infty 2^ka_{2^k} = a_1 + 2a_2 + 4a_4 + 8a_8 + \ldots
\]

*Theorem*

\[
\sum_{n=2}^\infty  \frac{1}{n (\log n)^p}
\]

converges when p is greater than one, and diverges otherwise.


** Root and ratio test

*Theorem (Root test)*
Given $\sum a_n$, put $\alpha = \lim_{n\to\infty}\sup\sqrt[n]{|a_n|}$

If $\alpha < 1$, it converges, if $\alpha > 1$, it diverges.

*Theorem (Ratio test)*

A series converges if $\lim_{n\to\infty} \vert\frac{a_{n+1}}{a_n}\vert < 1$, and diverges if the sequence is monotonically increasing at some finite point.


*Theorem*

\[
\lim_{n\to\infty} \frac{c_{n+1}}{c_n} \leq \lim_{n\to\infty} \inf \sqrt[n]{c_n}
\]

\[
\lim_{n\to\infty} \sup \sqrt[n]{c_n} \leq \lim_{n\to\infty} \sup \frac{c_{n+1}}{c_n}
\]

*Theorem*

Given a power series $\sum c_n z^n$, put $\alpha = \lim_{n\to\infty}\sup \sqrt[n]{|c_n|}$, and $R = \alpha^{-1}$. Then the series converges if $|z| < R$, and diverges if $|z| > R$.

*** Summation by parts

\[
\sum_{n=p}^q a_n b_n = \sum_{n=p}^{q-1} A_n (b_n - b_{n+1}) + A_q b_q - A_{p-1}b_p
\]

*Theorem*

If:
1. The partial sums of $A_n$ of $a_n$ form a bounded sequence.
2. $\{b_n\}$ is monotonoically decreasing
3. $\lim_{n\to\infty}b_n = 0$

Then $\sum a_n b_n$ converges.

*Theorem*
If:
1. $\{|c_n|\}$ is a monotonically decreasing sequence.
2. $\{c_n\}$ is an alternating series.
3. $\lim_{n\to\infty}c_n = 0$.

   Then $\sum c_n$ converges.

*** Absolute convergence

If a series converges absolutely, then it converges regularly. But a convergent series may not converge absolutely. Consider $(-1)^n / n$.

*Theorem*

If $\sum a_n$ converges absolutely, and $c_n = \sum_{k=0}^n a_k b_{n-k}$, then $\sum_{n=0}^\infty c_n = AB$

This theorem also holds if no assumption is made iwth absolute convergence.

*** Rearrangements

*Theorem (Riemann)*

Let $\sum a_n$ be a series of real numbers which converges but not absolutely. Suppose $-\infty \leq \alpha \leq \beta \leq \infty$. Then there exists a rearrangement $\sum a'_n$ with partial sums $s'_n$ such that:

\[
\lim_{n\to\infty}\inf s'_n = \alpha
\]

\[
\lim_{n\to\infty}\sup s'_n = \beta
\]

If $\sum a_n$ is a series of complex numbers which converges absolutely, then every rearrangement of $\sum a_n$ converges, and they all converge to the same sum.

* Continuity

*Definition*

Let X and Y be metric spaces, suppose $E \subset X$, f maps E into Y, and p is a limit point of E.

We say $ \lim_{x\to p}f(x) = q$, if there is a point $q \in Y$ with the property:

For every $\epsilon > 0$, there exists a $\delta > 0$ such that $d_Y(f(x),q) < \epsilon$ for all points $x\in E$ for which $0 < d_X(x,p) < \delta$.

*Theorem*

$\lim_{x \to p} f(x) = q$ iff $\lim_{n \to \infty} f(p_n) = q$ for every sequence $\{p_n\}$ in E such that $p_n \neq p$, $\lim_{n \to \infty} p_n = p$.

This also says that this limit is unique.

*Definition*

f is continuous at p if for every $\epsilon > 0$, there exists a $delta > 0$ such that $d_Y(f(x),f(p)) < \epsilon$ for all points $x \in E$ for which $d_X(x,p) < \delta$.

If p is also a limit point of E, then f is continuous at p iff $\lim_{x \to p} f(x) = f(p)$.

*Theorem*

A mapping f of a metric space X into a metric space Y is continous on X iff $f^{-1}(V)$ is open/closed in X for every open/closed set V in Y.


** Compactness

A mapping into $R^n$ is bounded if there is a real number M such that $| \bm{f}(x) | \leq M$ for all x.

*Theorem*

If f is a continuous mapping of a compact metric space X into a metric space Y, then f(X) is compact.

*Theorem*

If f is a continuous mapping of a compact metric space X into $R^n$, then f(X) is closed and bounded, thus f is bounded.

*Theorem*

Suppose f is a continous real function on a compact metric space X, and:

\[
M = \sup_{p\in X} f(p)
\]

\[
m = \inf_{p\in X}f(p)
\]

Then there exists points $p,q \in X$ such that $f(p) = M$ and $f(q) = m$.

*Theorem*

Suppose f is a continous, injective mapping of a copmact metric space X onto a metric space Y. The inverse mapping is a continous mapping of Y onto x.

*Theorem*

A mapping f is /uniformly continuous/ on X if for every $\epsilon > 0$, there exists $\delta > 0$ such that:

\[
d_Y(f(p),f(q)) < \epsilon
\]

for all p,q in X for which $d_X(p,q) < \delta$

*Theorem*

Let f be a continuous mapping of a compact metric space X into a metric space Y. Then f is uniformly continuous on X.

*Theorem* - Compactness is essential

Let E be a noncompact set in $R^1$. Then:

1. There exists a continuous function on E which is not bounded.
2. There exists a continuous and bounded function on E which has no maximum.

If in addition E is bounded, then:

3. There exists a continuous function on E which is not uniformly continuous.


*Theorem*

If f is a continuous mapping of a metric space X into a metric space Y, and if E is a connected subset of X, then f(E) is connected.

*Theorem* - Intermediate value theorem

Let f be a continuous real function on the interval [a,b]. If f(a) < f(b), and if c is a number such that f(a) < c f(b), then there exists a point $x \in (a,b)$ such that $f(x) = c$


** Monotonic functions

*Theorem*

f(x+) and f(x-) exist at every point for monotonic functions. That is, monotonic functions have no discontinuities of the second kind.

*Theorem*

Let f be monotonic on (a,b). Then the set of points at which f is discontinuous is at most countable. (you can establish a 1-1 correspondence between E and a subset of the rational numbers)

* Differentiation

** Mean value theorems

*Theorem* - Generalised mean theorem

If f and g are continuous real functions on [a,b] which are differential in (a,b), then there is a point $x\in(a,b)$ at which:

\[
[f(b)-f(a)]g'(x) = [g(b)-g(a)]f'(x)
\]

Since when defining $h(t) =[f(b)-f(a)]g(x) = [g(b)-g(a)]f(x)$, $h(a) = h(b)$.

** Continuity of derivatives
*Theorem*

Suppose f is real differentiable function on [a,b] and suppose $f'(a) < \lambda < f'(b)$, then there exists a point where $f'(x) = \lambda$.

It also means f' does not have any simple discontinuities.

** Taylor's theorem

The error of a taylor expansion about $\alpha$ up to the n-1th derivative at $\beta$ is equal to:

\[
R(\beta) = \frac{f^{(n)}(x)}{n!} (\beta - \alpha)^n
\]

for some x between $\beta - \alpha$

* Riemann-Stieltjes Integral

*Definition*

Let $[a,b]$ be a given interval. By a /partition/ P of [a,b], we mean a finite set of points $a=x_0,x_1,\ldots,x_n=b$, where $x_i < x_{i+1}$.


Suppose f is a bounded real function defined on $[a,b]$. Corresponding to each partition, we put:

\[
M_i = \sup f(x), x\in [x_{i-1},x_i]
\]
\[
m_i = \inf f(x), x\in [x_{i-1},x_i]
\]

\[
U(P,f) = \sum_{i=1}^n M_i \Delta x_i
\]

\[
L(P,f) = \sum_{i=1}^n m_i \Delta x_i
\]

\[
\overline{\int_a^b} f \dd{x} = \inf U(P,f)
\]

\[
\underline{\int_a^b} f \dd{x} = \sup L(P,f)
\]

where inf and sup are taken over all partitions P of [a,b].

When the upper and lower integrals are equal, we say that f is Riemann-integrable on $[a,b]$, we write $f \in \mathcal{R}$, where $\mathcal{R}$ denotes the set of Riemann-integrable functions.


Let $\alpha$ be a monotonically increasing function on [a,b]. Letting $\Delta\alpha_i = \alpha(x_i) - \alpha(x_{i-1})$. Replacing $x$ with $\alpha$, we get the Stieltjes integral.

** Refinement

*Definition*

A partition $P^*$ is a refinement of P if $P^* \supset P$. Given two partitions $P_1$ and $P_2$, $P^*$ is their common refinement if $P^* = P_1 \cup P_2$.

*Theorem*

\[
L(P,f,\alpha) \leq L(P^*,f,\alpha)
\]

\[
U(P^*,f,\alpha) \leq U(P,f,\alpha)
\]

*Theorem*

$f \in \mathcal{R}(\alpha)$ on [a,b] iff for every $\epsilon > 0$ there exists a partition P such that:

\[
U(P,f,\alpha) - L(P,f,\alpha) < \epsilon
\]

Additional properties:

1. If the equation holds for some P and $\epsilon$, then it holds (with the same $\epsilon$) for every refinement of P.
2. If it holds for $P = \{x_0,\ldots,x_n\}$, and if $s_i,t_i$ are arbitrary points in $[x_{i-1},x_i]$, then:
\[
\sum_{i=1}^n \vert f(s_i) - f(t_i) \vert \Delta \alpha_i < \epsilon
\]

3. If $f \in \mathcal{R}(\alpha)$ and the hypotheses of 2. hold, then:

\[
\left\vert \sum_{i=1}^n f(t_i)\Delta\alpha_i - \int_a^b f\dd{\alpha} \right\vert < \epsilon
\]

*Theorem*

If f is continuous on $[a,b]$, then $f \in \mathcal{R}(\alpha)$ on [a,b].

*Theorem*

If f is monotonic on [a,b], and if $\alpha$ is continuous on [a,b], then $f \in \mathcal{R}(\alpha)$.

*Theorem*

If f is bounded on [a,b], f has only finitely many points of discontinuity on [a,b], and $\alpha$ is continuous at every point at which f is discontinuous. Then $f \in \mathcal{R}(\alpha)$.

* Sequences and series of functions


** Uniform convergence

A sequence of functions $\{f_n\}$ converges uniformly on E to a function f if for every $\epsilon > 0$, there is an integer N such that $n \geq N$ implies:

\[
\vert f_n(x) - f(x) \vert \leq \epsilon
\]

for all $x \in E$.


Whereas if the sequence converges pointwise on E, there is an N depending on $\epsilon$ and $x$ such that epsilon-delta holds. If it converges uniformly on E, there is an N that will do for all $x \in E$.

*Theorem* - Cauchy criterion

The sequence of functions $\{f_n\}$ definde on E converges uniform;y on E iff for every $\epsilon > 0$ there exists an integer N such that $m,n \geq N$, $x \in E$ implies:

\[
\vert f_n(x) - f_m(x) \vert \leq \epsilon
\]

*Theorem*

Suppose $f_n(x) \to f(x)$. Let:

\[
M_n = \sup_{x\in E}\vert f_n(x) - f(x) \vert
\]

Then $f_n \to f$ uniformly on E iff $M_n \to 0$ as $n \to \infty$.


*Theorem* - Weierstrass

Suppose $\{f_n\}$ is a sequence of functions defined on E, and suppose:

\[
\vert f_n(x) \vert \leq M_n
\]

for all x and n.

Then $\sum f_n$ converges uniformly on E if $\sum M_n$ converges.

Note that the converse is not true.


*Theorem*

Suppose $f_n \to f$ uniformly on a set E in a metric space. Let $x$ be a limit point of $E$ and suppose that:

\[
\lim_{t\to x}f_n(t) = A_n
\]

Then $\{A_n\}$ converges, and:

\[
\lim_{t\to x}f(t) = \lim_{n\to\infty}A_n$
\]

That is to say:

\[
\lim_{t\to x} \lim_{n\to\infty} f_n(t) = \lim_{n\to\infty}\lim_{t\to x}f_n(t)
\]

*Theorem*

If $\{f_n\}$ is a sequence of continuous functions on E, and if $f_n \to f$ uniformly on E, then if f is continuous on E.

*Theorem*

Suppose K is compact,

1. $\{f_n\}$ is a sequence of continuous functions on K
2. $\{f_n\}$ converges pointwise to a continuous function f on K.
3. $\{f_n\}$ is a monotonically decreasing sequence.

Then $f_n \to f$ uniformly on K.

*Definition*

If X is a metric space, $\mathcal{C}(X)$ denotes the set of all complex-valued, continuous, bounded functions with domain X.

A supremum norm metric makes it into a metric space.

** Integration

*Theorem*

If $f_n \to f$ uniformly.

\[
\int_a^b f \dd{\alpha} = \lim_{n\to\infty}\int_a^b f_n \dd{\alpha}
\]

if f is a series, then this implies we can integrate term by term if it converges uniformly on the closed integration interval.

** Differentiation

*Theorem*

On a closed interval, if $\{f'_n\}$ converges uniformly, then $\{f_n\}$ converges uniformly and:

\[
f'(x) = \lim_{n\to\infty}f'_n(x)
\].

** Equicontinuity


*** Motivating examples

1. If a sequence of functions are pointwise bounded on $E$ and $E_1$ is a countable subset of $E$, it is always possible to find a subsequence such that the sequence converges for all $x\inE_1$.
2. But even if a sequence of continuous functions are uniformly bounded on a compact set $E$, there need not exist a subsequence that converges pointwise on $E$.
3. Every convergent sequence need not contain a uniformly convergent subsequence.


*** Equicontinuity

*Definition*

A familly of complex functions is said to be *equicontinuous* on E if for every $\epsilon > 0, \exists \delta > 0$ such that:

\[
\vert f(x) - f(y) \vert < \epsilon
\]

whenevery $d(x,y) < \delta, \forall x,y$.

*Theorem*

If $\{f_n\}$ is a pointwise bounded sequence of complex functions on a countable set $E$, then $\{f_n\}$ has a subsequence that converges for every $x \in E$.

*Theorem*

If $K$ is a compact metric space, $f_n \in \mathcal{C}(K)$ and $\{f_n\}$ converges uniformly on $K$, then $\{f_n\}$ is equicontinuous on K.

*Theorem*

If $K$ is compact, $f_n \in \mathcal{C}(K)$ and $\{f_n\}$ is pointwise bounded and equicontinuous,

1. $\{f_n\}$ is uniformly bounded on $K$. (all $f_i$ are bounded by a single $M$)
2. $\{f_n\}$ contains a uniformly convergent subsequence.


** Stone-Weierstrass theorem

*Theorem (Weierstrass theorem)*

If $f$ is a continuous complex function on $[a,b]$, there exists a sequence of polynomials $P_n$ such that $\lim_{n\to\infty} P_n(x) = f(x)$ uniformly on [a,b].

*Corollary*

For every interval $[-a,a]$ there is a sequence of real polynomials $P_n$ such that $P_n(0) = 0$ and such that $\lim_{n\to\infty}P_n(x) = |x|$ uniformly on $[-a,a]$.

*** Algebras

*Definition*

A family of complex functions defined on a set is said to be an *algebra* if it is clsoed under addition, muilitplication and scalar multiplication. Its *uniform closure* is the set of all functions which are the limits of uniformly convergent sequences of members of that algebra. An algebra is *uniformly closed* if $f \in \mathcal{A}$ whenever $f_n \in \mathcal{A}$ and they converge uniformly.

For example, the set of all polynomials is an algebra, and the Weierstrass theorem says that the set of all continuous functions is the uniform closure of the set of polynomials on [a,b].


*Theorem*

A uniform closure of an algebra of bounded functions is a uniformly closed algebra.

*Definition*

A family of functions $\mathcal{A}$ on a set $E$ is said to *seperate points* on $E$ if to every pair of distinct points $x_1,x2 \in E$, there corresponds a function $f \in \mathcal{A}$ such that $f(x_1) \neq f(x_2)$. If to each $x \in E$ there corresponds a function in $\mathcal{A}$ which does not vanish at $x$, we say *$\mathcal{A}$ vanishes at no point of $E$*.


*Theorem*

If an algebra of functions seperates points on and vanishes at no point of a set, then it contains a function such that $f(x_1) = c_1$ and $f(x_2) = c_2$.


*Theorem (Stone's extension)*

Let $\mathcal{A}$ be an algebra of real continuous functions on a compact set $K$. If $\mathcal{A}$ seperates points on $K$ and if $\mathcal{A}$ vanishes at no point of $K$, then the uniform closure of $\mathcal{A}$ consists of all real continous functions on $K$.

Note: The conclusion of this theorem holds for complex algebra only if the algebra is self-adjoint (it contains its complex conjugates).

*Theorem*

Let $\mathcal{A}$ be a self-adjoint algebra of complex continuous functions on a compact set $K$. If $\mathcal{A}$ seperates points on $K$ and if $\mathcal{A}$ vanishes at no point of $K$, then the uniform closure of $\mathcal{A}$ consists of all complex continous functions on $K$, i.e. $\mathcal{A}$ is dense $\mathcal{C}(K)$.

* Special functions

** Power series

Power series converge uniformly on a closed interval within the radius of convergence.

*Theorem (Abel's theorem)*

\[
\lim_{x\to 1} \sum_{n=0}^\infty c_n x^n = \sum_{n=0}^\infty c_n
\]

*Theorem*

Given a double sequence $\{a_{ij}\}$, suppose $\sum_{j=1}^\infty |a_{ij}| = b_i$ and $\sum b_i$ converges. Then double summations of $a_{ij}$ can be reversed.

*Theorem*

Let $E$ be the set of all $x \in S$ at which:

\[
\sum^\infty_{n=0} a_n x^n = \sum_{n=0}^\infty b_n x^n
\]

if $E$ has a limit point in S, then $a_n = b_n$.

* Multivariate functions

*Theorem*

A linear operator on a vector space is one-to-one iff its range is all of that vector space.

*Theorem*

Let $\Omega$ be the set of all invertible linear operators on $R^n$.

1. If $A \in \Omega, B \in L(R^n)$ and:

\[
\norm{B - A}\cdot \norm{A^{-1}} < 1
\]

then $B \in \Omega$.

2.$\Omega$ is an open subset of $L(R^n)$ and the mapping $A \to A^{-1}$ is continuous on $\Omega$.

** Differentiation

*Theorem*

Suppose $\bm{f}$ maps a convex open set $E \subset R^n$ into $R^m$, $\bm{f}$ is differentiable in $E$, and there is a real number $M$ such that:

\[
\norm{\bm{f}'(\bm{x})} \leq M
\]

for every $\bm{X} \in E$. Then:

\[
\vert \bm{f(b) - f(a)} \vert \leq  M \vert \bm{b - a} \vert
\]

for all $a,b \in E$.

*Corollary*

If $\bm{f'(x) = 0}$ for all $x \in E$, then $\bm{f}$ is constant.

*Definition*

A differentiable mapping $\bm{f}$ of an open set $E \subset R^n$ into $R^m$ is said to be *continuously differentiable* in $E$ if $\bm{f'}$ is a continuous mapping of $E$ into $L(R^n,R^m)$.

We also say that $\bm{f} \in \mathcal{C}'(E)$ or it is a $\mathcal{C}'$-mapping.

*Theorem*

Suppose $\bm{f}$ maps an open set $E \subset R^n$ into $R^m$. Then $\bm{f}\in\mathcal{C}'(E)$ iff all the partial derivatives of $f$ exist and are continuous on $E$.


** Contraction

*Definition*

Let $X$ be a metric space. If $\phi$ maps $X \to X$, and if there is a number $c < 1$, such that:

\[
d(\phi(x),\phi(y)) \leq c d(x,y)
\]

for all $x,y\in X$, then $\phi$ is a a contraction of $X$ into $X$.

*Theorem*

If $X$ is a complete metric space, then there exists only one $x \in X$ such that $\phi(x) = x$


** Inverse function theorem

*Theorem*

Suppose $\bm{f}$ is a $\mathcal{C}'$ -mapping of an open set $E \subset R^n \to R^n$, $\bm{f'(a)}$ is invertible for some $\bm{a} \in E$ and $\bm{b = f(a)}$. Then:

1. There exists open sets $U,V \subset R^n$ such that $\bm{a} \in U, \bm{b} \in V$, $\bm{f}$ is one-to-one on $U$, and $f(U) = V$.
2. If $\bm{g}$ is the inverse of $\bm{f}$ (which exists by (1)), defined in $V$, then $\bm{g} \in \mathcal{C}'(V)$


As a consequence of (1),

*Theorem*

IF $\bm{f}$ is a $\mathcal{C}'$ -mapping of an open set $E \subset R^n \to R^n$, $\bm{f'(a)}$ is invertible for some $\bm{a} \in E$, then $\bm{f}(W)$ is an open subset of $R^n$ for every open set $W \subset E$. i.e. $\bm{f}$ is an open mapping of $E$ into $R^n$.

** Implicit function theorem


*Theorem*

Let $\bm{f}$ be a $\mathcal{C}'$ -mapping of $E \subset R^n \to R^m$, such that $\bm{f(a,b)}$ vanishes for some point $\bm{(a,b)} \in E$. Put $A = \bm{f'(a,b)}$ and assume $A_x$ is invertible. Then there exists open sets $U \subset R^{n+m}$ and $W \subset R^m$ with the property, To every $\bm{y}\in W$, corresponds a unique $\bm{x}$ such that $\bm{f}(\bm{x,y})$ vanishes. If this $\bm{x}$ is defined to be $\bm{g(y)}$, $\bm{g'(b)} = -(A_x)^{-1}A_y$.

** Rank theorem

*Theorem*

Suppose $m,n,r$ are nonnegative integers, $m,n \geq r$,$\bm{F}$ is a $\mathcal{C}'$ -mapping of an open set $E \subset R^n \to R^m$, and $\bm{F'(x)}$ has rank $r$ for every for every $\bm{x}\in E$. Fix $\bm{a}\in E$, put $A = \bm{F'(a)}$, and let $Y_1$ be the range of $A$, and let $P$ be a projection in $R^m$ whose range is $Y_1$. Let $Y_2$ be the null space of $P$.
Then there are open sets $U,V \in R^n$, with $\bm{a} \in U \subset E$ and there is a 1-1 $\mathcal{C}'$-mapping $\bm{H}$ of $V$ onto $U$, (whose inverse is also of class $\mathcal{C}'$) such that:

\[
\bm{F(H(x))} = A\bm{x} + \phi(Ax)
\]

for all $x\in V$, where $\phi$ is a $\mathcal{C}'$ - mapping of the open set $A(V) \subset Y_1$ into $Y_2$.

*Theorem*

When $f \in \mathcal{C}''(E)$

\[
D_{21} f = D_{12} f
\]

** Differentiation of Integrals


*Theorem*

To insert an derivative into an integral, note that the integrand has to continuous wrt the differentiation variable.

* Integration of differential forms

*Theorem*

For every $f\in\mathcal{C}(I_k)$, $L(f) = L'(f)$.

*Definition*

The support of a complex function on $R^k$ is the closure of the set of all points $\bm{x} \in R^k$ at which $f(\bm{x})\neq 0$.

** Primitive mappings

*Definition*

If $\bm{G}$ maps on a open set $E \subset R^n \to R^n$, and if there is an integer $m$ and a real function $g$ with domain $E$ such that $G(x) = \sum_{i\neq m} x_i \bm{e}_i + g(\bm{x})\bm{e}_m$, then $\bm{G}$ is primitive. (i.e. it changes at most one coordinate)

The jacobian of $\bm{G}$ at $\bm{a}$ is given by $J_{\bm{G}} (\bm{a}) = \det \bm{G}'(\bm{a}) = (D_m g)(\bm{a})$.

*Definition*

A linear operator that interchanges some members of the standard basis is called a *flip*.

*Theorem*

Suppose $\bm{F}$ is a $\mathcal{C}'$ mapping of an open set $\E \subset R^n \to R^n$, $\bm{0} \in E$, $\bm{F(0)=0}$, and $\bm{F'(0)}$ is invertible. Then there is a neighbourhood of $\bm{0}$ in $R^n$ in which a representation:

\[
\bm{F(x)} = B_1\ldots B_{n-1} G_n \circ\ldots\circ G_1 (x)
\]

is valid.

Each $\bm{G}_i$ is a primitive $\mathcal{C}'$ is a primitive $\mathcal{C}'$ -mapping in some neighborhood of $\bm{0}$ ; $\bm{G_i(0)=0}$, $\bm{G_i'(0)}$ is invertible and each $B_i$ is either a flip or identity operator.


** Partitions of unity

*Theorem*

Suppose $K$ is a compact subset of $R^n$ and $\{V_\alpha\}$ is an open cover of $K$. Then there exists functions $\psi_1,\ldots,\psi_s \in \mathcal{C}'(R^n)$ such that:

1. $0 \leq \psi_i \leq 1$
2. each $\psi_i$ has its support in some $V_\alpha$, and
3. $\sum_i \psi_i(\bm{x}) = 1$ for every $\bm{x} \in K$

Thus, $\{\psi_i\}$ is called a *parition of unity* and (b) is expressed by saying that $\{\psi_i\}$ is *subordinate* to the cover $\{V_\alpha\}$.

** Differential forms

*Definition*

To say that $\bm{f}$ is a $\mathcal{C}'$ -mapping of a compact set $D \subset R^k$ into $R^n$ means that there is a $\mathcal{C}'$ mapping $g$ of an open set $W \subset R^k, D\subset W$ into $R^n$ such that $\bm{g(x)= f(x)}$ for all $\bm{x} \in D$.

*Definition*

Suppose $E$ is an open set in $R^n$. A *k-surface* in $E$ is a $\mathcal{C}'$ mapping $\Phi$ from a compact set $D \subset R^k$ into $E$.  $D$ is called the *parameter domain* of $\Phi$. (Points of $D$ will be denoted by $\bm{u}$).

For example, 1-surfaces are the same as continuously differentiable curves.

*Definition*

Suppose $E$ is an open set in $R^n$. A differential form of order $k \geq 1$ in $E$ (a k-form in E) is a function $\omega$:

\[
\omega = \sum a_{i_1 \ldots i_k}(\bm{x}) \dd{x_{i_1}} \wedge \ldots \wedge \dd{x_{i_k}}
\]

which assigns to each k-surface $\phi$ in E a number $\omega(\Phi) = \int_\Phi \omega$, according to the rule:

\[
\int_\Phi \omega = \int_D \sum a_{i_1 \ldots i_k}(\Phi(\bm{u})) \frac{\partial(x_i_1,\ldots,x_i_k)}{\partial(u_1,\ldots,u_k)}  \dd{\bm{u}}
\]

*** Examples

A k-form is said to be of class $\mathcal{C}'$ or $\mathcal{C}''$ if the functions $a_{i_k\ldots i_k}$ are all of class $\mathcal{C}'$ or $\mathcal{C}''$.

A 0-form in $E$ is defined to be continuous function in $E$.

Integrals of 1-forms are called line integrals.



*** Standard presentation


\[
\omega = \sum_j b_{I}(\bm{x}) \dd{x_I}
\]

where the $I$ is a set of increasing k-indices.

*Theorem*

If $\omega = 0$ in $E$, then $b_{I}(\bm{x}) = 0$ for every increasing k-inex $I$ for every $\bm{x} \in E$


*** Product of forms

\[
\dd{x_I} \wedge \dd{X_J} = (-1)^\alpha \dd{x_{[I,J]}}
\]

where $\alpha$ is the number of differences $j_t - i_s$ that are /negative/.

*Theorem*

1. If $\omega$ and $\lambda$ are k- and m- forms respectively, of class $\mathcal{C}'$ in E, then:

\[
d(\omega \wedge \lambda) = \dd{\omega} \wedge \lambda + (-1)^k \omega \wedge \dd{\lambda}
\]

*** Change of variables

Suppose $E$ is an open set in $R^n$, T is an $\mathcal{C}'$ mapping of E into an open set $V \subset R^m$, and $\omega$ is a k-form in $V$, whose standard presentation is:

\[
\omega = \sum_I b_I(y) \dd{y}_I
\]
Let $t_1,\ldots,t_m$ be the components of $T$; If:

\[
\bm{y} = (y_1,\ldots,y_m) = T(\bm{x})
\]

then $y_i = t_i(\bm{x})$.

\[
\dd{t_i} = \sum_{j=1}^n (D_j t_i)(\bm{x})\dd{x_j}
\]

Thus each $\dd{t_i}$ is a 1-form in $E$.

The mapping $T$ transforms $\omega$ into a k-form $\omega_T$ in $E$, whose definition is:

\[
\omega_T = \sum_I b_I(T(\bm{x})) \dd{t_{i_1}} \wedge \ldots\wedge \dd{t_{i_k}}
\]

*Theorem*

Let $\omega,\lambda$ be k- and m-forms respectively.

1. $(\omega + \lambda)_T = \omega_T + \lambda_T$ if $k=m$
2. $(\omega \wedge \lambda)_T = \omega_T \wedge \lambda_T$
3. $\dd{\omega_T} = (\dd{\omega})_T$ if $\omega$ is of class $\mathcal{C}'$ and $T$ is of class $\mathcal{C}''$.

*Theorem*

Suppose $\omega$ is a k-form in an open set $E \subset R^n$, $\Phi$ is a k-surface in $E$, with parameter domain $D \subset R^k$, and $\Delta$ is the k-surface in $R^k$, with paramter domain $D$, definde by $\Delta(\bm{u}) = \bm{u}(u\in D)$. Then:

\[
\int_\Phi \omega = \int_\Delta \omega_\Phi
\]

Proof by using jacobian.

*Theorem*

Suppose $T$ is a $\mathcal{C}'$ mapping of an open set $E \subset R^n$ into an open set $V \subset R^m$, $\Phi$ is a k-surface in $E$, and $\omega$ is a k-form in $V$. Then:

\[
\int_{T\Phi} \omega = \int_\Phi \omega_T
\]

Proof by using the previous theorems


*** Simplex and chains


*Definition (Affine simplexes)*

A mapping $\bm{f}$ that carries a vector space $X$ into a vector space $Y$ is said to be *affine* if $\bm{f} - \bm{f(0)}$ is linear. i.e.

\[
\bm{f(x) = f(0)} + A \bm{x}
\]

for some $A \in L(X,Y)$.


We define the *standard simplex* $Q^k$ to be the set of all $\bm{u} \in R^k$ of the form:

\[
\bm{u} = \sum_{i=1}^k \alpha_i \bm{e}_i
\]

such that $\alpha_i \geq 0$ and $\sum\alpha_i \leq 1$.

The *oriented affine k-simplex*:

\[
\sigma = [\bm{p_0,p_1,\ldots,p_k}]
\]

is defined to be the k-surface in $R^n$ with parameter domain $Q^k$ which is given by t
