#+TITLE: Electrodynamics
#+STARTUP: latexpreview

* Electrostatics

** Relations

V -> rho

\[
\laplacian V = -\frac{\rho}{\epsilon_0}
\]
rho -> V

\[
V = \frac{1}{4\pi\epsilon_0}\int\frac{\rho}{r}\dd{\tau}
\]

E -> rho

\[
\div{E} = \frac{\rho}{\epsilon_0}
\]

rho -> E

\[
E = \frac{1}{4\pi\epsilon_0}\int\frac{\rho{\bf \hat{r}}}{r^2}\dd{\tau}
\]

V -> E

\[
E = -\grad{V}
\]

E -> V
\[
V = -\int{E \cdot \dd{l}}
\]

** Potential energy

For a configuration,


\begin{align*}
W & = \frac{1}{8\pi\epsilon_0}\sum_{i=1}^n\sum_{j\neq i}^n \frac{q_iq_j}{r_{ij}} \\
& = \frac12 \sum_{i=1}^n q_i V(\bf r_i) \\
\end{align*}

For a continuous charge distribution,

\begin{align*}
W & = \frac12 \int \rho V \dd{\tau} \\
& = \frac{\epsilon_0}{2}\left(\int_V E^2 \dd{\tau} + \oint_S VE\cdot\dd{\bf a}\right) \\
& = \frac{\epsilon_0}{2}\int E^2 \dd{\tau} \text{(all space)}
\end{align*}

For compount systems:

\[
W = W_1 + W_2 + \epsilon_0 \int{E_1 \cdot E_2}\dd{\tau}
\]

* Potentials

Laplace's equations tolerates no local maxima and minima and at a point it can often be expressed as the average of the surrounding potential.

The potential at the center of a sphere is equal to the average potential at the surface due to an external charge located a distance from the center of the sphere. v_ave = V_center + kQ_enc/R

** Boundary conditions and uniqueness theorems

*** First uniqueness theorem
The solution to Laplace's equation in some volume is uniquely determined if potential is specified on the boundary surface S and the charge density throughout the region is specified.

*** 2nd uniqueness theorem

In a volume surrounded by conductors and containing a specifed charge density, the electric field is uniquely determined if the total charge on each conductor is given.

** Method of images

Suppose a point charge q is held a distance d above an infinite grounded conducting plane. What is the potential (which is affected by the accumulation of charge on the plane).

Solution: Pretend there is a charge at -z. Many quantities end up being the same though, Energy is not the same. Note you cannot put image charges where yuo are calculating V as it would change charge density.

** Seperation of variables

set boundary conditions and you will get hyperbolic (suited for boundary conditions at infinity)and trig functions. then find fourier coeffs

*** Spherical coordinates

\[
V(r,\theta) = \sum^\infty_{l=0}\left(A_lr^l + \frac{B_l}{r^{l+1}}\right) P_l(\cos\theta)
\]

where P are the legendre polynomials:

\[
P_l(x) = \frac{1}{2^l l!} \left(\dv{x}\right)^l (x^2 - 1)^l
\]

** Multipole expansion


\[
V(\bm{r}) = \frac{1}{4\pi\epsilon_0}\sum_{n=0}^\infty \frac{1}{r^{n+1}}\int(r')^n P_n(cos\alpha)\rho(\bm{r}')\dd{\tau'}
\]

where $\alpha$ is the angle between r and r'

*** Dipole

Dipole moment:

\[
\bm{p} \equiv \int \bm{r}' \rho(\bm{r}') \dd{\tau}
\]

or $\sum_i q_i\bm{r}'_i$. or $\bm{p} - Q\bm{a}$ for a shift in coordiantes.

\[
V_{dip}(r) = \frac{1}{4\pi\epsilon_0}\frac{\bm{p}\cdot\hat{\bm{r}}}{r^2}
\]

for a pure dipole (as opposed to a physical one), qd = constant but d -> 0 and

* Electric fields in matter

** Induced dipole

An atom which is placed in an electric field gets polarised and forms a dipole. the dipole moment is given by.

\[
\bm{p} = \alpha \bm{E}
\]
