#+TITLE: Evaluating Effects of Height on Different Speed Bump Profiles

* Goals
 - Minimising the jolt (decreasing impulse/vertical acceleration)
 - maximise velocity loss over riding them
 - Check what type of shape is best for speed bumps, trapezoidal, sinusoidal, segment of circle, parabolic, maybe custom shape etc.
* Experiment
** Independent variable
   - For each speed bump profile, vary the height of the speed bump, (i.e. vary
the constant factor , $a$, of the function describing the curve of the speed
bump,  $f(x) = a . sin(x)$ or $f(x) = ax^2$)

** dependant variable
   - For each speed bump profile, measure the remaining distance travelled by
the vehicle function of speed bump.
* Set-up
  Insert pic

* Context
 - Speed bumps are an effective way of ensuring the road safety and whatever

* Safety
  - Not applicable

* Imprecisions
- friction in the system, (wheel and axle, wheel and ground) is
present. However, it is negligible between the wheel and axle and wheel and hump
and frictional force between the wheel and ground will be constant in all
set-ups thus acceleration will be constant and the displacement of the vehicle
can still be contrasted with other set-ups.
- Molding clay is a crude process can lead to minor imperfections in the precision of the mould to
the speed bump profile.

* Apparatus
- Phone camera
- Tracker and Logger to measure velocity and peak acceleration and plot a graph
- Toy car
- Moulding clay
- measuring tape
- Rulers to help with moulding clay
- Ramp and block to hoist ramp up
