# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-notes-page:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup emacs
        uses: purcell/setup-emacs@master
        with:
          version: 26.3
      - name: Clone Org-mode exporter
        run: git clone https://github.com/kaushalmodi/ox-hugo.git ox-hugo
      - name: Render config into hugo
        run: emacs -L ./ox-hugo -l ox-hugo.el --load exportscript.el --batch kill
      - run: ls .. -a
      - run: ls ~ -a
      - name: Pushes to shirator website
        uses: dmnemec/copy_file_to_another_repo_action@3fe42250d47e0764da9de9939b151b09a26e5857
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '~/hugo/content/posts/'
          destination_folder: 'public'
          destination_repo: 'Spongiforma/notes-page'
          destination_branch: 'master'
          user_email: 'bot@emacs.bot'
          user_name: 'emacs action'
